# Root
baseURL = 'https://arcade.aao.fyi/clickinbad/'
languageCode = 'en'
theme = 'codeberg.org/aao-fyi/shock'

# Info
title = 'ClickinBad'
copyright = 'ClickinBad Contributors'

# Features
disableHugoGeneratorInject = false
disableKinds = ['RSS','taxanomy','term']
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Build
[build]
  # PostCSS
  writeStats = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.146.0'
  # Logo
  [[module.imports]]
    path = 'codeberg.org/aao-fyi/project-logos'
  [[module.imports.mounts]]
    source = 'arcade-clickinbad'
    target = 'assets/img/logo/'

# Footer
[menu]
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    url = 'https://aao.fyi/privacy/'
  [[menu.footer]]
    identifier = 'sitemap'
    name = 'Sitemap'
    url = '/sitemap.xml'
